### ISSUE TITLE
🐛[BUG] Layout menu does not close when on mobile screen

### ISSUE THREAD

**Issue by xXAvoraXx** [ant-design/pro-components#6305]
### 🐛 bug 描述

Layout menu doesn't close when mobile is on screen size. There is no maskClosable property.

### 🏞 期望结果 | Expected results

The maskClosable property must be present.

### 💻 复现代码 | Recurrence code

![Capture111](https://user-images.githubusercontent.com/6988989/203997214-e4658f5a-b4ad-46c0-ac7a-731e43247eec.PNG)

### © 版本信息

- Ant Design Pro 版本: 4.23.3
- umi 版本: 4.0.24
- 浏览器环境: Chrome
- 开发环境 Windows

**Comment by chenshuai2144** [comment]
fixed in 06a892093

**Comment by xXAvoraXx** [comment]
> fixed in [06a8920](https://github.com/ant-design/pro-components/commit/06a8920933a7a956df0895bf8b2922499ae1075a)

Has this issue been updated? Where can I update this? app.tsx?

**Comment by xXAvoraXx** [comment]
I see this problem still persists when I install the latest version of pro ant design. @chenshuai2144
